### ISSUE TITLE
Multiple Commentsections per Page possible? 

### ISSUE THREAD

**Issue by Donderda** [glosa/glosa-static-integration#4]
Hi,
I want to simulate a comment behavior like ifixit uses (e.g. https://www.ifixit.com/Guide/Acer+Aspire+5336-2524+Battery+Replacement/128765): A comment section below every step. Is isso able to achieve this with glosa?

Can you provide any tips?

**Comment by tanrax** [comment]
@Donderda Hello, of course you can achieve to imitate it and even improve it. That's what Glosa is there for.

I can tell you that it all starts with https://github.com/glosa/glosa-server . As soon as you have the server up and running you can give a comment box to any page. You can use the https://github.com/glosa/glosa-static-integration repository as a template. But basically it's nothing you can't do with Javascript and AJAX.

Another thing, you are not reporting a bug, you are consulting. Next time write me through my page 🙂 : https://programadorwebvalencia.com/ . Best regards
