### ISSUE TITLE
I've try include to my site, but it's turn out that the comments are not show.

### ISSUE THREAD

**Issue by phondanai** [glosa/glosa-static-integration#8]
I've try to integrate with Cryogen static websit tool.
By using {% include %} tag in the template.
Comments retrieval seems correct (by inspecting network activity and it's show JSON data from comment server).

Here's the output from comment section.
![comments](https://user-images.githubusercontent.com/662302/120075038-e2258000-c0c9-11eb-8562-48551506ce52.png)

or you can see it's live at [Here](https://blog.nowaveform.me/posts-output/2021-05-21-first-post/)

Thanks.

**Comment by tanrax** [comment]
As far as I can see it works, but when drawing the text of the comment it does not show it. 
```
curl https://glosa.nowaveform.me/api/v1/comments/\?url\=https://blog.nowaveform.me/posts-output/2021-05-21-first-post/
```

Have you modified any element?

**Comment by tanrax** [comment]
@phondanai I am seeing the comments perfectly. I suspect that something has been modified in the HTML, in the template.
![imagen](https://user-images.githubusercontent.com/4553672/120098132-73c9d780-c134-11eb-8390-dd4ca7567a99.png)

**Comment by tanrax** [comment]
You code

```
<div class="comment__content"></div>
```

My code

```
<div class="comment__content">{{ filterHTMLTags(fields.message) }}</div>
```

Since you are using a static generator, it will have interpreted the {{}} variables and deleted them.

**Comment by phondanai** [comment]
Thank you for your kind response. 
I will check the template that cause the problem.

**Comment by phondanai** [comment]
It's work!
Just like your suggestion, the problem is cause by Selmer template engine using by Cryogen.
![fixed](https://user-images.githubusercontent.com/662302/120098597-0aac8900-c161-11eb-9a9c-b32b92e6a91f.png)
